name: Resize images

on:
  push:
    branches:
      - stage

permissions:
  contents: write

jobs:
  build:
    name: Resize Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stage
        uses: actions/checkout@v6
        with:
          ref: stage
      - name: Resize Images
        uses: xprilion/img-resizer-inplace@v1
        with:
          target: "docs/assets"
          dimensions: "2048x2048"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
      
